pipeline {
    agent any
    tools {
        maven "maven"
        jdk "jdk11"
    }
    
    
    stages {
        stage('Build') {
            steps {
                echo 'build'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                echo 'Test'
                sh 'mvn test'
            }
           
        }
        stage('Deliver') {
            steps {
                echo 'deliver'
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
